### ISSUE TITLE
[Bug]:表格中存在多列rowSpan时多页rowSpan错误

### ISSUE THREAD

**Issue by dongfangjiamu** [CcSimple/vue-plugin-hiprint#104]
### 使用的版本

latest

### 你的安装方式

NPM 依赖

### 你的操作系统

Windows

### 你的浏览器

Chrome

### 你的项目编程语言

Vue 2

### 问题描述

从左边拖过来的表格元件，如果数据超过一页，第2页的排版会错乱掉，原因是某些列的单元格的rowspan的值变成该页的行数，会纵向合并单元格，导致整个表格变形

### 如何复现

1、从左边拖过一个表格
2、将表格的数据记录设置得多一些（超过一页）
3、执行打印，或输出打印的html

### 预期结果

分页后，第2页的字段与第1页的表格保持一致，且排版正常

### 实际结果

分页后，第2页表格会多出几个空白列，原因是单元格的rowspan设置错误。

### 截图或视频

参考下面异常情况与正常情况的对比：
![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/27055764/caf813d4-37da-4094-a0b9-74f3a9bf4527)
![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/27055764/93fd4c7d-8fee-4ca2-93a6-e203c87d2c6e)

### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://github.com/CcSimple/vue-plugin-hiprint/issues)

**Comment by Xavier9896** [comment]
定位到问题主要在这里：
https://github.com/CcSimple/vue-plugin-hiprint/blob/571d53b520acaf363b745fe0cb109030fdb17401/src/hiprint/hiprint.bundle.js#L5816-L5850

nextRow 只定义了一个变量用于存储整个表格的 rowspan，但是实际可能多列都设置了 rowspan ，分页后需要为每列都重新计算 rowspan
