### ISSUE TITLE
[Bug]:火狐浏览器下打印，二维码展示是黑色的，谷歌浏览器又正常

### ISSUE THREAD

**Issue by 1451544363** [CcSimple/vue-plugin-hiprint#111]
### 使用的版本

latest

### 版本号

最新

### 你的安装方式

NPM 依赖

### 你的操作系统

Windows

### 你的浏览器

Chrome

### 你的项目编程语言

None

### 问题描述

显示

### 如何复现

显示

### 预期结果

显示

### 实际结果

显示

### 截图或视频

[在这里上传图片]

### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://github.com/CcSimple/vue-plugin-hiprint/issues)

**Comment by CcSimple** [comment]
那就用谷歌内核的浏览器。如下图，改换就换。 你如果有那精力，你也可以去调整适配 其他浏览器。
![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/24693863/2a2a8fa3-d8ef-4062-ba6f-cdee50259c67)
