### ISSUE TITLE
[Bug]:image toPdf的时候不能显示图片

### ISSUE THREAD

**Issue by 18626428291** [CcSimple/vue-plugin-hiprint#114]
### 使用的版本

latest

### 你的安装方式

NPM 依赖

### 你的操作系统

Windows

### 你的浏览器

Edge

### 你的项目编程语言

Vue 3

### 问题描述

![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/42088184/3827a8e0-310d-43a3-b646-6cb9f64864c6)
![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/42088184/a30d70ab-ade5-494f-936f-ace1503f34a0)
![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/42088184/c2e7c68d-833d-49bd-a81e-ec2e9b7b9ad8)
![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/42088184/de6e5783-006a-437e-ab9d-2913ad6d5962)
打印和预览都是正常的，但是导出图片或导出pdf是不显示，请问如何解决

### 如何复现

如上

### 预期结果

如上

### 实际结果

如上

### 截图或视频

[在这里上传图片]
![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/42088184/3827a8e0-310d-43a3-b646-6cb9f64864c6)
![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/42088184/a30d70ab-ade5-494f-936f-ace1503f34a0)
![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/42088184/c2e7c68d-833d-49bd-a81e-ec2e9b7b9ad8)
![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/42088184/de6e5783-006a-437e-ab9d-2913ad6d5962)

### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://github.com/CcSimple/vue-plugin-hiprint/issues)

**Comment by Xavier9896** [comment]
使用绝对路径而非相对路径试试发自我的 iPhone在 2024年3月24日，12:15，xujiajun ***@***.***> 写道：﻿
使用的版本
latest
版本号
No response
你的安装方式
NPM 依赖
你的操作系统
Windows
你的浏览器
Edge
你的项目编程语言
Vue 3
问题描述
image.png (view on web)
image.png (view on web)
image.png (view on web)
image.png (view on web)
打印和预览都是正常的，但是导出图片或导出pdf是不显示，请问如何解决
如何复现
如上
预期结果
如上
实际结果
如上
截图或视频
[在这里上传图片]
image.png (view on web)
image.png (view on web)
image.png (view on web)
image.png (view on web)
这个问题是否已经存在？

 我已经搜索过现有的问题 (https://github.com/CcSimple/vue-plugin-hiprint/issues)

**Comment by 18626428291** [comment]
使用了绝对定位连预览和在线打印都不能正常显示，目前配置如下
![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/42088184/2e7224c7-fc16-4107-94af-d73d36e5eb32)
只能放在public文件夹下
即使改成base64的方式也无法显示
这是我生成pdf的方法
![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/42088184/5d99de7c-2cb3-447b-90cc-fedeb385b8d5)
