### ISSUE TITLE
[Bug]:条形码不能隐藏“条形码：”前缀。

### ISSUE THREAD

**Issue by tong822218** [CcSimple/vue-plugin-hiprint#116]
### 使用的版本

latest

### 版本号

0.0.56

### 你的安装方式

NPM 依赖

### 你的操作系统

MacOS

### 你的浏览器

Chrome

### 你的项目编程语言

Vue 2

### 问题描述

条形码组件，打印的时候无法隐藏“条形码：” 前缀，只能是选择全部隐藏内容，或者全部显示内容
<img width="260" alt="image" src="https://github.com/CcSimple/vue-plugin-hiprint/assets/9926531/59d73e93-9765-4847-935b-383ac02b2f27">
我只想显示 23432

### 如何复现

1.打开演示demo
2.拖拽一个条形码组件到 模版中
3.没有参数可以隐藏掉  “条形码：” 这几个字

### 预期结果

不应该显示“条形码：”这几个字，一般二维码中都不会 写  “条形码：xxxx”，只显示 23432

### 实际结果

显示 条形码：23432

### 截图或视频

[在这里上传图片]
<img width="260" alt="image" src="https://github.com/CcSimple/vue-plugin-hiprint/assets/9926531/99be8550-a86b-4bb2-b6ed-5f6c76aca890">

### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://github.com/CcSimple/vue-plugin-hiprint/issues)

**Comment by Xavier9896** [comment]
v0.0.57-beta22 已默认移除 title
