### ISSUE TITLE
[Bug]:条形码选择旋转90度，显示效果和打印效果都发生错误

### ISSUE THREAD

**Issue by MrChen-Fly** [CcSimple/vue-plugin-hiprint#117]
### 使用的版本

latest

### 版本号

0.0.56

### 你的安装方式

NPM 依赖

### 你的操作系统

Windows

### 你的浏览器

其他

### 你的项目编程语言

Vue 3

### 问题描述

我正在开发物流面单打印模板，发现竖着打条码，样式效果发生变形

### 如何复现

1.添加条形码
2.样式中选择旋转角度，点击确定

### 预期结果

应该是竖着显示，宽高收到我的控制

### 实际结果

宽度溢出严重溢出

### 截图或视频

[在这里上传图片]
![企业微信截图_20240403155933](https://github.com/CcSimple/vue-plugin-hiprint/assets/26476602/96d54912-9046-4b02-b072-2f4de0c0550b)

### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://github.com/CcSimple/vue-plugin-hiprint/issues)

**Comment by CcSimple** [comment]
<img width="385" alt="image" src="https://github.com/user-attachments/assets/74463f23-cf43-4bb5-90e9-e213209d861d">
