### ISSUE TITLE
[Bug]:自启时无法隐藏打开应用

### ISSUE THREAD

**Issue by ywqwpp** [CcSimple/vue-plugin-hiprint#118]
### 使用的版本

latest

### 你的安装方式

下载源码 融合

### 你的操作系统

Windows

### 你的浏览器

Chrome

### 你的项目编程语言

None

### 问题描述

自启时无法隐藏打开应用

### 如何复现

自启

### 预期结果

隐藏到托盘

### 实际结果

窗口无法关闭

### 截图或视频

[在这里上传图片]

### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://github.com/CcSimple/vue-plugin-hiprint/issues)

**Comment by Xavier9896** [comment]
https://gitee.com/CcSimple/electron-hiprint/releases/tag/1.0.10
