### ISSUE TITLE
[Feature]: 如何实现即打即停

### ISSUE THREAD

**Issue by sandniu** [CcSimple/vue-plugin-hiprint#125]
### 你希望看到什么解决方案？

针对针式打印机，有即打即停的功能，也就是按照实际内容的高度打印，没有固定的页面高度。

### 意向参与贡献

- [X] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by Xavier9896** [comment]
参数面板 **分页规则** 有不分页的选项

但是我觉得这个选项可能不能解决你的问题，有多少内容打多少更常见于 **收银小票、超市小票** 使用的是 **行模式**，需要打印机支持 **省纸功能**（即设置打印机为最长纸张，遇到空白自动省纸不打印不走纸），需要你自己看看你使用的针式打印机是否支持省纸模式。

**Comment by sandniu** [comment]
谢谢您的回复！



是你说的那种打印机，也是那种使用场景。

设置不分页可以吗？到时候我试试看。

需要动态的去计算打印内容的高度吗？不分页的情况下，页面的高度是根据内容计算的吗？




再次感谢🙏

**Comment by Xavier9896** [comment]
不需要动态计算打印内容，只需要在 panel 的参数面板设置不分页即可，剩下的就是打印机需要设置最大纸张尺寸（POS 小票是如此）然后设置为省纸模式，不清楚针式是省纸还是行模式，你可以试试
