### ISSUE TITLE
[Bug]:表格列合并换页之后显示异常

### ISSUE THREAD

**Issue by LHMJessica** [CcSimple/vue-plugin-hiprint#126]
### 使用的版本

beta

### 版本号

0.0.57-beta23

### 你的安装方式

NPM 依赖

### 你的操作系统

Windows

### 你的浏览器

Chrome

### 你的项目编程语言

Vue 2

### 问题描述

[使用rowsColumnsMerge处理列合并，第一页合并显示正常，换页到第二页之后，表格开始变得诡异，贴图在后面。与issues[https://github.com/CcSimple/vue-plugin-hiprint/issues/87](url)是同一个问题

### 如何复现

使用我提供的打印数据和模板
[template.json](https://github.com/CcSimple/vue-plugin-hiprint/files/15465381/template.json)
[printData.json](https://github.com/CcSimple/vue-plugin-hiprint/files/15465383/printData.json)

### 预期结果

![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/49225908/92e70b50-304b-4ea4-893d-a7194a79da20)

### 实际结果

![334302855-c006065e-7531-410c-b353-a0a5c4bd3850](https://github.com/CcSimple/vue-plugin-hiprint/assets/49225908/d5b7f549-930e-4a0b-8e2a-819bb9134e2c)

### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://github.com/CcSimple/vue-plugin-hiprint/issues)

**Comment by CcSimple** [comment]
合并行数写的又问题吧。

测试改成 [1,1] 正常。

<img width="469" alt="image" src="https://github.com/CcSimple/vue-plugin-hiprint/assets/24693863/4c5343bc-988c-4965-a471-b39a1558a73f">

**Comment by 1241751430** [comment]
这个问题没有解决
