### ISSUE TITLE
[Bug]:在使用 `vue-plugin-hiprint` 插件时，遇到 `qrcode.js` 报错 "Cannot read properties of undefined (reading '_android')"。

### ISSUE THREAD

**Issue by mopisces** [CcSimple/vue-plugin-hiprint#128]
### 使用的版本

beta

### 版本号

0.0.50

### 你的安装方式

NPM 依赖

### 你的操作系统

Windows

### 你的浏览器

Chrome

### 你的项目编程语言

Vue 3

### 问题描述

初始化插件时浏览器控制台报错。

### 如何复现

1.安装 `vue-plugin-hiprint`
2.初始化插件

### 预期结果

二维码能正确生成，不会报错。

### 实际结果

报错 "Cannot read properties of undefined (reading '_android')"

### 截图或视频

![1717809589294(1)](https://github.com/CcSimple/vue-plugin-hiprint/assets/31386799/4620db4d-5b87-4c0e-a111-442a5c5a7cc5)

### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://github.com/CcSimple/vue-plugin-hiprint/issues)

**Comment by CcSimple** [comment]
更新版本时候， 我记得修复过此问题。 有git history 查看qrcode.js 更新记录
