### ISSUE TITLE
[Feature]: 组件字段名称改成下拉选择后，设置初始值以后，可以禁止该值再次修改么

### ISSUE THREAD

**Issue by killdada** [CcSimple/vue-plugin-hiprint#132]
### 你的功能建议是否和某个问题相关？

![image](https://github.com/user-attachments/assets/5aed6687-f788-404c-a361-d974b5a7ac21)
我们预设的模板里面，有些字段名称是固定禁止修改的，这里的下拉组件能否再加个disabled配置

### 你希望看到什么解决方案？

组件字段名称改成下拉选择后，设置初始值以后，可以禁止该值再次修改么

### 意向参与贡献

- [X] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by CcSimple** [comment]
文章：参数篇。 自己重写参数
