### ISSUE TITLE
[Feature]: 开发分支上的条形码与之前的不兼容，希望文字可以单独调整样式

### ISSUE THREAD

**Issue by mzzya** [CcSimple/vue-plugin-hiprint#133]
### 你的功能建议是否和某个问题相关？

1.从0.0.57-beta19（包括）如果设置了条码的字段名，但是不传值会显示文字次格式不支持该文本，18之前是没问题的

<img width="462" alt="image" src="https://github.com/user-attachments/assets/9c21bc0b-c27a-4179-ae51-d5f879e68bff">

2.条码文字样式跟以前不一样
<img width="298" alt="image" src="https://github.com/user-attachments/assets/1a62147a-b86e-4619-9b5f-fc85502ae6c0">

### 你希望看到什么解决方案？

1.条码不传值不要显示任何文字。

虽然现在可以通过自定义样式函数设置颜色为白色跳过，但是不兼容，直接升级老的模板全要检查。

2.条码的文字样式希望可以能配置。

### 意向参与贡献

- [X] #134

**Comment by CcSimple** [comment]
@Xavier9896 之前优化条码的部分，考虑兼容之前版本。应该加一个选项，用户自主选择是否启用。 默认不启用。

**Comment by CcSimple** [comment]
0.0.57-beta30 已调整：默认原版本 单独文本 渲染 
<img width="231" alt="image" src="https://github.com/user-attachments/assets/33cfc2d2-07c7-4f03-8612-7dd282abba52">
