### ISSUE TITLE
[Bug]: 版本由0.0.50 更新到0.0.56版本以后，自定义参数挂载到文本以后，文本点击拖拽报错，

### ISSUE THREAD

**Issue by killdada** [CcSimple/vue-plugin-hiprint#135]
### 使用的版本

latest

### 版本号

0.0.56

### 你的安装方式

NPM 依赖

### 你的操作系统

Windows

### 你的浏览器

Chrome

### 你的项目编程语言

Vue 3

### 问题描述

版本由0.0.50 更新到0.0.56版本以后，自定义参数挂载到文本以后，文本点击拖拽报错，
可复现的git地址
https://github.com/killdada/vue-plugin-hiprint-start

### 如何复现

1： yarn yarn serve
2:  点击文本报错

### 预期结果

正常拖拽

### 实际结果

控制台报错

### 截图或视频

[在这里上传图片]

### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://github.com/CcSimple/vue-plugin-hiprint/issues)

**Comment by CcSimple** [comment]
报错截图 都没有😓

**Comment by killdada** [comment]
![image](https://github.com/user-attachments/assets/bd3018ca-55b8-4923-a570-fb8a3b907624), 

这种更新 
![image](https://github.com/user-attachments/assets/a2e401bb-6d99-496a-af17-4b8aa3162bc7)
跟上面的demo一样报错

**Comment by CcSimple** [comment]
好好看看文章，参数篇。 哪里来的写法？

https://mp.weixin.qq.com/s/vfgSG62tAXn7Ot7y3x68fw
