### ISSUE TITLE
[Feature]: 打印重叠

### ISSUE THREAD

**Issue by killdada** [CcSimple/vue-plugin-hiprint#136]
### 你的功能建议是否和某个问题相关？

![image](https://github.com/user-attachments/assets/8d5ea88f-8040-4657-a2fc-af5a63a93522)

项目单独跑正常，当使用无界嵌入到其他应用时，
![image](https://github.com/user-attachments/assets/9ecd600c-93f3-41af-8eac-6231516d27fc)
d打印内容重叠

看无界嵌入子应用时，把css改成了内敛的形式，

然后尝试了1：
![image](https://github.com/user-attachments/assets/8822ae8c-8aa7-4bab-9103-4b508967e5b8)

2: 主应用直接嵌入该css文件

都无法解决该问题

### 你希望看到什么解决方案？

作为无界子应用内嵌时，打印不重叠

### 意向参与贡献

- [X] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by CcSimple** [comment]
注意 media="print"
