### ISSUE TITLE
[Bug]打印客户端交互bug

### ISSUE THREAD

**Issue by lwg1998** [CcSimple/vue-plugin-hiprint#140]
### 使用的版本

latest

### 你的安装方式

NPM 依赖

### 你的操作系统

Windows

### 你的浏览器

Chrome

### 你的项目编程语言

None

### 问题描述

第二次通过双击桌面图标打开软件时，屏幕会闪烁一下软件界面然后再次隐藏掉。

### 如何复现

1.打开软件
2.点击关闭按钮，最小化到托盘
3.再次通过双击桌面图标的方式打开软件

### 预期结果

预期会再次展示主界面

### 实际结果

实际屏幕会闪烁一下软件界面然后重新回到系统托盘再次隐藏掉

### 截图或视频

[在这里上传图片]

### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://github.com/CcSimple/vue-plugin-hiprint/issues)

**Comment by CcSimple** [comment]
在客户端仓库 提issue
