### ISSUE TITLE
[Question]: 如何实现条形码表格与普通文本表格在一页中打印

### ISSUE THREAD

**Issue by Whiteyingshan** [CcSimple/vue-plugin-hiprint#142]
### 你的功能建议是否和某个问题相关？

现在想要实现每一页中显示一个条形码与一个普通文本，但是使用表格会让条形码全部显示之后才显示普通文本表格

### 你希望看到什么解决方案？

显示一个条形码后，显示普通文本；每次这样循环

### 你考虑过哪些替代方案？

尝试过让条形码表格在页眉线以上，但这样会只打印第一个条形码
![微信截图_20240929152754](https://github.com/user-attachments/assets/cc6e19a6-5083-4f97-81c1-0b848090de60)

### 你有其他上下文或截图吗？

以下是打印模板：
![微信截图_20240929151707](https://github.com/user-attachments/assets/26d690eb-1067-497a-8cd8-a080f321f72a)

以下是预览：
![微信截图_20240929151523](https://github.com/user-attachments/assets/15e3934a-586f-4300-86ef-161c86e98efc)

### 意向参与贡献

- [x] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by CcSimple** [comment]
打印数据传数组 就是了。 文档！文档！文档！
