### ISSUE TITLE
当页眉线在页脚线下时会导致预览卡死

### ISSUE THREAD

**Issue by boskt** [CcSimple/vue-plugin-hiprint#17]
当调整页面尺寸后可能会导致页眉线在页脚线下，在预览时就会出现卡死情况，经过调试发现hiprintTemplate.getHtml() 该方法存在问题，猜测该方法内部出现判断错误，导致内部不停循环。

**Comment by CcSimple** [comment]
因为table分页处理问题，导致死循环了。
0.0.29-3 已修复此问题

**Comment by boskt** [comment]
新的BUG产生，当表格某个字段内容过多时，也会卡死
