### ISSUE TITLE
图片打印时不显示

### ISSUE THREAD

**Issue by cnsdwu** [CcSimple/vue-plugin-hiprint#19]
![image](https://user-images.githubusercontent.com/23513790/191634079-2e99b52e-de77-4be1-b38b-ae25150ce19f.png)
这是示例地址打的

**Comment by Xavier9896** [comment]
demo里面的图片只是css样式显示，图片元素实际未绑定对应地址
![image](https://user-images.githubusercontent.com/34981520/191634340-380df701-e5ed-4c3e-8db2-d51064a875e2.png)
你需要在这里配置图片的地址才能实现打印时显示
![image](https://user-images.githubusercontent.com/34981520/191634476-239b6d2f-cf28-4fe6-a326-96ae66c9f8db.png)
