### ISSUE TITLE
通过panel.addPrintText方式添加的文本，超出宽度的内容如果是英文或数字不会自动换行

### ISSUE THREAD

**Issue by 814096703** [CcSimple/vue-plugin-hiprint#20]
`let panel = hiprintTemplate.addPrintPanel({
    width: 50,
    height: 10,
    paperFooter: 0,
    paperHeader: 0,
    paperNumberDisabled: true,
  });

  panel.addPrintText({
    options: {
      width: 40,
      height: 15,
      top: 5,
      left: 9,
      title: ’langlanglanglanglanglanglanglanglanglanglanglanglanglanglanglang‘
      textType: 'text',
      fontSize: 6,
    },
  });`

**Comment by CcSimple** [comment]
我测试可以正常换行呀。
```
    let panel2 = hiprintTemplate.addPrintPanel({
      width: 50,
      height: 10,
      paperFooter: 0,
      paperHeader: 0,
      paperNumberDisabled: true,
    });
    panel2.addPrintText({
      options: {
        width: 40,
        height: 15,
        top: 5,
        left: 9,
        title: 'langlanglanglanglanglanglanglanglanglanglanglanglanglanglanglang',
        textType: 'text',
        fontSize: 6,
      },
    });
    hiprintTemplate.design('#hiprint-printTemplate');
```

**Comment by 814096703** [comment]
已经解决了，我全局引入print-lock.css，再把组件写上field，把数据打包成json data，最后把数据用hiprintTemplate.print(data)方法打印，一切正常。
之前是把数据直接拼接在options的title里的，排版怎么都不对。
