### ISSUE TITLE
当使用.print2会出现TypeError: p.each is not a function

### ISSUE THREAD

**Issue by BoneBee** [CcSimple/vue-plugin-hiprint#21]
Uncaught (in promise) TypeError: p.each is not a function
    at b.print2 (vue-plugin-hiprint.js:6026:96)
    at n.$print2 (vue-plugin-hiprint.js:6767:1)
    at VueComponent.handlePreviewOpened (index.vue:483:1)
    at _callee$ (index.vue:454:1)
    at tryCatch (runtime.js:45:15)
    at Generator.invoke [as _invoke] (runtime.js:274:1)
    at prototype.<computed> [as next] (runtime.js:97:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:16)
    at _next (asyncToGenerator.js:25:9)

b.prototype.print2 = function (o, r) {
                            var a, l, s, p, I;
                            o = o || {}, r = r || {}, this.clientIsOpened() ? (a = this, s = {}, p = (l = 0) < jquery__WEBPACK_IMPORTED_MODULE_0___default()('link[media=print][href*="print-lock.css"]').length ? jquery__WEBPACK_IMPORTED_MODULE_0___default()('link[media=print][href*="print-lock.css"]') : [], I = "", r.styleHandler && (I += r.styleHandler()), p.each(function (i, t) {

**Comment by Xavier9896** [comment]
<link rel="stylesheet" type="text/css" media="print" href="https://cdn.jsdelivr.net/npm/vue-plugin-hiprint@latest/dist/print-lock.css">

<link rel="stylesheet" type="text/css" media="print" href="/print-lock.css">

**Comment by Xavier9896** [comment]
```html
<!--【必须】在index.html （一般在 public目录下）文件中添加打印所需样式(此cdn可能不稳定):-->
<link rel="stylesheet" type="text/css" media="print" href="https://cdn.jsdelivr.net/npm/vue-plugin-hiprint@latest/dist/print-lock.css">
<!-- 可以调整成 相对链接/自有链接, 【重要】名称需要一致 【print-lock.css】-->
<link rel="stylesheet" type="text/css" media="print" href="/print-lock.css">
```

**Comment by BoneBee** [comment]
使用npm vue没有index.html应该放到哪里

**Comment by BoneBee** [comment]
使用 this.$print2 字体存在失真的问题

**Comment by BoneBee** [comment]
hiprintTemplate.print(printData, {furnaceLotNumber: 'dawdad'})
使用这种原生的写法无法赋值

**Comment by Xavier9896** [comment]
> hiprintTemplate.print(printData, {furnaceLotNumber: 'dawdad'}) 使用这种原生的写法无法赋值

没有 `furnaceLotNumber ` 这个属性吧

**Comment by BoneBee** [comment]
有的，所有属性都无法显示，不用hiprintTemplate.print直接用this.$print2才有值

**Comment by BoneBee** [comment]
找到问题了第一个参需要给的是属性值json搞反了😂
