### ISSUE TITLE
打印表格问题

### ISSUE THREAD

**Issue by zhuangzehua** [CcSimple/vue-plugin-hiprint#22]
1. ### **表格每页距离页眉线和页尾线的距离不一致**

![image](https://user-images.githubusercontent.com/104714357/205479739-b914b03b-f0cb-4d0e-af25-d2f5c26371ce.png)

3.   **自动补全功能autoCompletion超出页尾线**

![1670139653746](https://user-images.githubusercontent.com/104714357/205479816-7ee8bbe4-d265-4f80-afe8-0a3fc83c83fd.png)

**Comment by CcSimple** [comment]
测试未发现第一个问题
第二个问题已修复， 试试 0.0.39-beta2
