### ISSUE TITLE
对齐api hiprintTemplate.setElsAlign不生效

### ISSUE THREAD

**Issue by zhoujingfu** [CcSimple/vue-plugin-hiprint#26]
对齐api hiprintTemplate.setElsAlign不生效，作者有空麻烦看一下，谢谢

**Comment by Xavier9896** [comment]
有框选元素吗？或者按住ctrl/command选中多个元素？发自我的 iPhone在 2023年1月5日，12:10，zhoujingfu ***@***.***> 写道：﻿
对齐api hiprintTemplate.setElsAlign不生效，作者有空麻烦看一下，谢谢

**Comment by zhoujingfu** [comment]
不好意思看到代码了，我以为是元素内的文本对齐，原来是多个元素对齐

**Comment by Xavier9896** [comment]
有个方法可以设置文本的对齐方式，更新记录里面有。有加微信群吗？群里交流吧。

发自我的 iPhone

**Comment by Xavier9896** [comment]
https://github.com/CcSimple/vue-plugin-hiprint/blob/main/CHANGELOG.md#0026-2022-07-07

**Comment by zhoujingfu** [comment]
> 有个方法可以设置文本的对齐方式，更新记录里面有。有加微信群吗？群里交流吧。 发自我的 iPhone

好的，我加一下
