### ISSUE TITLE
vue-cli4 webpack 如何引用

### ISSUE THREAD

**Issue by rebider** [CcSimple/vue-plugin-hiprint#3]

**Comment by CcSimple** [comment]
**1.控制台中输入 以安装npm包**
```npm install vue-plugin-hiprint```
**2.在index.html 文件中添加打印所需样式: 当然你也可以调整成 相对链接/自有链接**
```<link rel="stylesheet" type="text/css" media="print" href="https://cdn.jsdelivr.net/npm/vue-plugin-hiprint@latest/dist/print-lock.css">```
