### ISSUE TITLE
无法初始化， hiprint.init()

### ISSUE THREAD

**Issue by PromiseAll** [CcSimple/vue-plugin-hiprint#31]
刚刚更新0.0.46 版本无法启动，初始化时 hiprint.init()  回退一个版本可以正常使用

**Comment by PromiseAll** [comment]
![image](https://user-images.githubusercontent.com/56338627/220859026-f2dfa3e4-fd59-4f54-b8c5-ed646b8fa80d.png)
![image](https://user-images.githubusercontent.com/56338627/220859075-b094954d-e47b-401f-afd0-3c6177fb8ad9.png)

**Comment by Xavier9896** [comment]
不应该啊，线上demo都是正常的，demo是在每次提交代码的时候自动构建的，如果有问题的话demo也会有问题才对

**Comment by PromiseAll** [comment]
> 不应该啊，线上demo都是正常的，demo是在每次提交代码的时候自动构建的，如果有问题的话demo也会有问题才对

我怀疑是我 hiprint.init() 时没有传任何参数，demo里是有参数的

**Comment by CcSimple** [comment]
这个错误错误很明显啊;  应该是我删除一点代码导致的。看这里 [ea42452f7f99adb355f1b06316ceded4a259e4cd](https://github.com/CcSimple/vue-plugin-hiprint/commit/ea42452f7f99adb355f1b06316ceded4a259e4cd)

```JavaScript
hiprint.init({
  providers: []
})
```
这样就好了

或者稍微处理一下源码 ：

```JavaScript
p.a.instance.init(t), p.a.instance.providers && p.a.instance.providers.forEach(function (t) {
    t.addElementTypes(a.instance);
  });
```
