### ISSUE TITLE
表格 footerFormatter函数，除options外其他参数为空

### ISSUE THREAD

**Issue by twy-141** [CcSimple/vue-plugin-hiprint#37]
footerFormatter: function (options, rows, data, currentPageGridRowsData) {
// 在表格末尾做统计，发现除了options，其他参数在打印的时候为空或undefined
}

**Comment by CcSimple** [comment]
测试 demo2【自定义设计】有返回对应值：
<img width="1585" alt="image" src="https://user-images.githubusercontent.com/24693863/225288181-aba9a34e-949c-476d-9593-39317efc5fe1.png">
