### ISSUE TITLE
添加表格fields下拉字段后，没办通过其他方式手输改变

### ISSUE THREAD

**Issue by htx7** [CcSimple/vue-plugin-hiprint#38]
![image](https://user-images.githubusercontent.com/69007221/234785634-bd3d4f90-58b8-4eea-8190-a34fb8d22c8b.png)
![image](https://user-images.githubusercontent.com/69007221/234785816-5a4dce35-530b-4762-af70-d0305a1f0ed6.png)
![image](https://user-images.githubusercontent.com/69007221/234786138-85bd417b-b5b0-4c7d-9c4b-6f51a21e2deb.png)

**Comment by CcSimple** [comment]
正常情况，双击有下拉选择框的。 不知道是不是你配置有什么问题。

**Comment by Xavier9896** [comment]
双击切换的问题是这样的，你需要保持fields与columns中的title一致


你可以用【单元格渲染函数】或【单元格格式化函数】自行渲染或格式化为任意自定义类型
```js
function(value,row,index,options){ return dayjs(value).format('YYYY-MM-DD HH:mm:ss');}
```
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CcSimple/vue-plugin-hiprint"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月3日(星期三) 晚上8:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [CcSimple/vue-plugin-hiprint] 添加表格fields下拉字段后，没办通过其他方式手输改变 (Issue #38)





  
正常情况，双击有下拉选择框的。不知道是不是你配置有什么问题。
  
不好意思，我没描述清楚，下拉能正常显示，但是我通过左侧配置栏设置好标题后，双击标题他又会变成之前的标题，重要下拉的设置的text属性也就是标题和字段名 不一致，双击他时会变回去
 
此外我还遇到一个问题，表格中的日期没办法进行格式化，他只提供了少数的字段类型

**Comment by htx7** [comment]
> 双击切换的问题是这样的，你需要保持fields与columns中的title一致 你可以用【单元格渲染函数】或【单元格格式化函数】自行渲染或格式化为任意自定义类型 ```js function(value,row,index,options){ return dayjs(value).format('YYYY-MM-DD HH:mm:ss');} ``` ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CcSimple/vue-plugin-hiprint" ***@***.***&gt;; 发送时间:&nbsp;2023年5月3日(星期三) 晚上8:25 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;Re: [CcSimple/vue-plugin-hiprint] 添加表格fields下拉字段后，没办通过其他方式手输改变 (Issue #38) 正常情况，双击有下拉选择框的。不知道是不是你配置有什么问题。 不好意思，我没描述清楚，下拉能正常显示，但是我通过左侧配置栏设置好标题后，双击标题他又会变成之前的标题，重要下拉的设置的text属性也就是标题和字段名 不一致，双击他时会变回去 此外我还遇到一个问题，表格中的日期没办法进行格式化，他只提供了少数的字段类型 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

谢谢你的回复，我之前有尝试添加【单元格渲染函数】或【单元格格式化函数】，但具体那列是日期型的这是不确定的，并且如果能直接选择，或输入格式会更好，我该这么做
