### ISSUE TITLE
预览和直接打印PDF 表格边框宽度显示不一致

### ISSUE THREAD

**Issue by mzzya** [CcSimple/vue-plugin-hiprint#39]
<img width="999" alt="image" src="https://user-images.githubusercontent.com/19657992/236120834-28b3cf02-a2eb-4fef-9145-6c02f1bab957.png">

如图，直接打印pdf时表格宽度比预览时要宽一些，有没有办法处理？

**Comment by CcSimple** [comment]
最新预览版，调整了表格边框相关参数。 相对来说，没这么粗了
