### ISSUE TITLE
请问，文本选择字段名称后，怎么不显示冒号。 另外是不是字段打印值都是title,看官网是data

### ISSUE THREAD

**Issue by vhaixingv** [CcSimple/vue-plugin-hiprint#40]

**Comment by CcSimple** [comment]
可以看看文章： 使用-打印篇

[使用-打印篇](https://mp.weixin.qq.com/s/P-Zz8YfELmRNi4EuED4QmA)

<img width="743" alt="image" src="https://github.com/CcSimple/vue-plugin-hiprint/assets/24693863/54666390-d652-4068-81a8-1d359bd705ec">
