### ISSUE TITLE
修改配置后，需要重新聚焦才能再次修改

### ISSUE THREAD

**Issue by htx7** [CcSimple/vue-plugin-hiprint#41]
问题描述
我在选中文本元素添加边框时，添加左侧边框后，提交后，想继续添加右侧边框， 但他不会生效，需要重新聚焦文本元素后才能添加右边框
包括选中表格栏位进行修改配置时，进行修改行高时也是同等问题， 也无法继续修改

**Comment by CcSimple** [comment]
线上 demo 测试没有这个情况。 不知道是不是你用的 老版本，获取其他版本。

**Comment by htx7** [comment]
更新最新版本还是一样，难道我不小心做了什么。

**Comment by CcSimple** [comment]
线上demo为准！ 其他情况，我就不知道咯

**Comment by htx7** [comment]
> 线上演示！其他情况，我不知道咯
不好意思哈，确实是我不小心造成的，因为在onDataChanged 添加  修改字段名，动态修改下拉的数据，然后更新模板造成的
