### ISSUE TITLE
code128C 怎么不支持

### ISSUE THREAD

**Issue by figo361** [CcSimple/vue-plugin-hiprint#46]
![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/6834921/b5c1601c-e830-4ffa-bc8c-219a571b97b2)

**Comment by figo361** [comment]
原来是码长度不够

**Comment by Xavier9896** [comment]
是你的testData不支持该格式，不同的条形码、二维码支持的内容格式是不一致的，显示不支持就是你的内容格式不对，有可能是长度、格式等等。
