### ISSUE TITLE
整体放大，再对元素字体缩小，点击元素时跳动

### ISSUE THREAD

**Issue by Yamcanda** [CcSimple/vue-plugin-hiprint#49]
![pic1](https://github.com/CcSimple/vue-plugin-hiprint/assets/119381663/203e19b8-d02e-439a-8057-5426dc6616dd)

**Comment by CcSimple** [comment]
元素中的缩放是 自定义扩展的属性，没有处理过。所以有这个bug

**Comment by Yamcanda** [comment]
> 元素中的缩放是 自定义扩展的属性，没有处理过。所以有这个bug

无法修复？

**Comment by CcSimple** [comment]
> > 元素中的缩放是 自定义扩展的属性，没有处理过。所以有这个bug
> 
> 
> 
> 无法修复？

没空去研究
