### ISSUE TITLE
动态修改表格下拉 🤪

### ISSUE THREAD

**Issue by htx7** [CcSimple/vue-plugin-hiprint#52]
请问有没有办法，有两个下拉列表，动态修改表格字段名，更新字段对应的下拉列表。
<img width="1466" alt="image" src="https://github.com/CcSimple/vue-plugin-hiprint/assets/69007221/918f77d7-092a-4e3a-8b30-09108268b8e4">

**Comment by CcSimple** [comment]
重写表格 字段名的 参数

**Comment by htx7** [comment]
好的，谢谢
