### ISSUE TITLE
当设置分组字段函数后，序号列可否以整表数据去计算？

### ISSUE THREAD

**Issue by Johnnychenyao** [CcSimple/vue-plugin-hiprint#55]
【背景设置】：表格面板，
1、设置了《分组字段函数》和《分组脚格式化函数》后，
2、列属性，字段类型：序号，

目前默认的设置是以分组单独计算序号，可否加多个选项，可切换至整表计算，不受分页影响

**Comment by Johnnychenyao** [comment]
列设置中，单元格渲染函数，返回的index=0，不知道是否有误
function(value,row,index,options){ return '<td></td>'; }

**Comment by Xavier9896** [comment]
> 列设置中，单元格渲染函数，返回的index=0，不知道是否有误 function(value,row,index,options){ return ''; }

这个的确有人反馈，估计是个bug，这个应该好解决。

**Comment by Xavier9896** [comment]
考虑再三，为了解决此建议而添加一个选项实在是不可取，表格本来就已经有很多属性及配置，该建议也仅在设置分组字段函数后需要考虑，过多的设置及参数只会让 vue-plugin-hiprint 难以上手，不采纳该建议。

但是你仍然可以通过 分组函数+格式化函数 自行实现该需求：
1. 在传入 printData 数据前对数据进行排序，添加自定义“序号”字段
   > 当然你也可以在 分组字段函数 中进行这一步操作
2. 使用单元格格式化 / 单元格渲染函数 处理、渲染 “序号” 列
