### ISSUE TITLE
表格字段切换后 单元格格式化函数 没有随着字段变化改变成目的字段配置的自定义函数

### ISSUE THREAD

**Issue by xiaoqiaotq** [CcSimple/vue-plugin-hiprint#67]
![WX20230926-144750](https://github.com/CcSimple/vue-plugin-hiprint/assets/8088060/83a31798-a3e1-4a26-967f-6af724264e99)

**Comment by CcSimple** [comment]
只是单纯切换列的 字段名而已。 并没有切换整个列的功能
