### ISSUE TITLE
vue2.X项目安装使用出现exports is not defined问题

### ISSUE THREAD

**Issue by 0321long** [CcSimple/vue-plugin-hiprint#74]
项目运行完 npm install vue-plugin-hiprint
在main.js中引入使用，项目直接提示异常
![1111](https://github.com/CcSimple/vue-plugin-hiprint/assets/66344222/956f359b-cf41-4b2c-80eb-df9dddbf9b79)

**Comment by CcSimple** [comment]
估计是 nodejs 或者 webpack 版本问题呢。  

demo 是 nodejs 16.18.x   webpack 4.×
