### ISSUE TITLE
官网打印预览不显示测试数据问题

### ISSUE THREAD

**Issue by the-didi** [CcSimple/vue-plugin-hiprint#82]
1. 浏览器版本:
chrome 120.0.6099.129 正式版本

2. 出现问题:
我在使用vue-plugin-hiprint生成打印预览的时候，我发现我生成的打印预览无法预览到控件中填入的testData:
![1703251735092](https://github.com/CcSimple/vue-plugin-hiprint/assets/61458828/13721d9f-d5a7-4288-8ee5-d97938bbbfe6)
![1703251746234](https://github.com/CcSimple/vue-plugin-hiprint/assets/61458828/3ff30774-02a2-4541-800c-6c48ded39c38)

同时我在gitee的demo页面中预览测试数据也不能看到测试数据:
![1703251830145](https://github.com/CcSimple/vue-plugin-hiprint/assets/61458828/b8cfdf01-da72-49c4-a1ab-ad75cdbefc61)
![1703251850167](https://github.com/CcSimple/vue-plugin-hiprint/assets/61458828/4b4cbd74-35be-4117-b202-7b64cd1cb80e)
https://ccsimple.gitee.io/vue-plugin-hiprint/

我使用的版本是: "vue-plugin-hiprint": "0.0.55-beta20"

打印出来的pdf也是没有任何信息的,请问这个情况有人遇到过吗

**Comment by CcSimple** [comment]
这不是BUG。 建议先看看 打印篇 文章。

后面版本也有个API getTestData可以获取到 模板的 测试数据。

**Comment by the-didi** [comment]
> 这不是BUG。 建议先看看 打印篇 文章。
> 
> 后面版本也有个API getTestData可以获取到 模板的 测试数据。
是的 已解决，是我的问题，你的代码很稳定，这个issure可以close掉了
