### ISSUE TITLE
[Bug]：表格打印使用rowsColumnsMerge处理合并列，在表格打印到第二页时显示合并异常

### ISSUE THREAD

**Issue by LHMJessica** [CcSimple/vue-plugin-hiprint#87]
### 使用的版本

latest

### 版本号

0.0.56

### 你的安装方式

NPM 依赖

### 你的操作系统

Windows

### 你的浏览器

Chrome

### 你的项目编程语言

Vue 2

### 问题描述

表格数据中使用rowType字段来区分这一行是否需要合并,rowType=‘elsetype'时处理合并，在打印只有一页时显示正常，两页时，第二页合并列显示异常
```
  function(data, col, colIndex, rowIndex) {
   //其他费用templateGroupItemName列合并两个列
    if (data.rowType === 'elseitem' && col.field == 'templateGroupItemName') {
      return [1,2 ];
    } else if (data.rowType === 'elseitem' && col.field == 'templateGroupItemDesc') { 
       //其他费用templateGroupItemDesc列合并6个列
      return [1, 6];
    } else if (data.rowType === 'elseitem') { //其他费用项行其他列隐藏
      return [0, 0];
    }
   //其他单元格正常显示
    return [1, 1];
  }
```

### 如何复现

提供我使用的打印模板和打印数据预览可复现
[print-data.txt](https://github.com/CcSimple/vue-plugin-hiprint/files/13825981/print-data.txt)
[template.txt](https://github.com/CcSimple/vue-plugin-hiprint/files/13825982/template.txt)

### 预期结果

合并列正常显示

### 实际结果

不正常，第二页的第一行虽然合并了，但是应该隐藏的格子却显示了

### 截图或视频

[在这里上传图片]
![1704340133283](https://github.com/CcSimple/vue-plugin-hiprint/assets/49225908/94c68d76-7dd4-4372-afa9-0b848ec167ef)

### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://github.com/CcSimple/vue-plugin-hiprint/issues)

**Comment by Xavier9896** [comment]
最新beta版已修复colspan合并未隐藏问题，不过仍有另外一个问题：隐藏表头后合并表格宽度不正确
![image](https://github.com/CcSimple/vue-plugin-hiprint/assets/34981520/5fb871ac-5219-469e-bccf-b3fd51166228)
需要使用[colgroug](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/colgroup)及col修复，仍待解决
